# This YAML file contains the configuration options for several different
# JMS Providers
#
# The Examples that ship with jruby-jms will use the entry 'activemq' unless
# overriden at the command line. For example:
#    jruby producer.rb activemq
#

---
# Active MQ Centralized Broker
activemq:
  :factory: org.apache.activemq.ActiveMQConnectionFactory
  :broker_url: tcp://127.0.0.1:61616
  :username: system
  :password: manager
  :require_jars:
    - ~/Applications/apache-activemq-5.5.0/activemq-all-5.5.0.jar
    - ~/Applications/apache-activemq-5.5.0/lib/optional/slf4j-log4j12-1.5.11.jar
    - ~/Applications/apache-activemq-5.5.0/lib/optional/log4j-1.2.14.jar

# ActiveMQ In VM Broker (Supports messaging within a JVM instance)
activemq-invm:
  :factory: org.apache.activemq.ActiveMQConnectionFactory
  :broker_url: vm://mybroker
  :object_message_serialization_defered: true
  :require_jars:
    - ~/Applications/apache-activemq-5.5.0/activemq-all-5.5.0.jar
    - ~/Applications/apache-activemq-5.5.0/lib/optional/slf4j-log4j12-1.5.11.jar
    - ~/Applications/apache-activemq-5.5.0/lib/optional/log4j-1.2.14.jar

# ActiveMQ with failover to slave instance
activemq-ha:
  :factory: org.apache.activemq.ActiveMQConnectionFactory
  :broker_url: failover://(tcp://msg1:61616,tcp://msg2:61616)?randomize=false&timeout=30000&initialReconnectDelay=100&useExponentialBackOff=true
  :require_jars:
    - ~/Applications/apache-activemq-5.5.0/activemq-all-5.5.0.jar
    - ~/Applications/apache-activemq-5.5.0/lib/optional/slf4j-log4j12-1.5.11.jar
    - ~/Applications/apache-activemq-5.5.0/lib/optional/log4j-1.2.14.jar

# JBoss 4 Messaging
  :jndi_name: ConnectionFactory
  :jndi_context:
    java.naming.factory.initial: org.jnp.interfaces.NamingContextFactory
    java.naming.provider.url: jnp://localhost:1099
    java.naming.security.principal: user
    java.naming.security.credentials: pwd
  :require_jars:
    - ~/Applications/jboss-messaging-client/1.4.0.SP3/javassist.jar
    - ~/Applications/jboss-messaging-client/1.4.0.SP3/jboss-aop-jdk50.jar
    - ~/Applications/jboss-messaging-client/1.4.0.SP3/jboss-messaging-client.jar
    - ~/Applications/jboss-messaging-client/1.4.0.SP3/jbossall-client.jar
    - ~/Applications/jboss-messaging-client/1.4.0.SP3/trove.jar

# Apache Qpid
qpid:
  :jndi_name: local
  :jndi_context:
    java.naming.factory.initial: org.apache.qpid.jndi.PropertiesFileInitialContextFactory
    connectionfactory.local: amqp://guest:guest@clientid/testpath?brokerlist='tcp://localhost:5672'
  :require_jars:
    - ~/Applications/javax.jms.jar
    - ~/Applications/qpid-0.8/lib/backport-util-concurrent-2.2.jar
    - ~/Applications/qpid-0.8/lib/commons-collections-3.2.jar
    - ~/Applications/qpid-0.8/lib/commons-lang-2.2.jar
    - ~/Applications/qpid-0.8/lib/mina-core-1.0.1.jar
    - ~/Applications/qpid-0.8/lib/qpid-client-0.8.jar
    - ~/Applications/qpid-0.8/lib/qpid-common-0.8.jar
    - ~/Applications/qpid-0.8/lib/slf4j-api-1.6.1.jar
    - ~/Applications/qpid-0.8/lib/log4j-1.2.12.jar
    - ~/Applications/qpid-0.8/lib/slf4j-log4j12-1.6.1.jar

# HornetQ Broker
hornetq:
  # Connect to a local HornetQ Broker using JNDI
  :jndi_name: /ConnectionFactory
  :jndi_context:
    java.naming.factory.initial: org.jnp.interfaces.NamingContextFactory
    java.naming.provider.url: jnp://localhost:1099
    java.naming.factory.url.pkgs: org.jboss.naming:org.jnp.interfaces
    java.naming.security.principal: guest
    java.naming.security.credentials: guest
  :require_jars:
    - ~/Applications/hornetq-2.2.2.Final/lib/hornetq-core-client.jar
    - ~/Applications/hornetq-2.2.2.Final/lib/hornetq-core.jar
    - ~/Applications/hornetq-2.2.2.Final/lib/hornetq-jms-client.jar
    - ~/Applications/hornetq-2.2.2.Final/lib/jboss-jms-api.jar
    - ~/Applications/hornetq-2.2.2.Final/lib/jnp-client.jar
    - ~/Applications/hornetq-2.2.2.Final/lib/netty.jar

# IBM WebSphere MQ
wmq:
  :factory: com.ibm.mq.jms.MQQueueConnectionFactory
  :queue_manager: LOCAL
  :host_name: localhost
  :channel: MY.CLIENT.CHL
  :port: 1414
  # Transport Type: com.ibm.mq.jms.JMSC::MQJMS_TP_CLIENT_MQ_TCPIP
  :transport_type: 1
  :username: mqm
  :require_jars:
    - /opt/mqm/lib/com.ibm.mqjms.jar

# Oracle AQ 9
oracleaq:
  :factory => 'JMS::OracleAQConnectionFactory',
  :url => 'jdbc:oracle:thin:@hostname:1521:instanceid',
  :username => 'aquser',
  :password => 'mypassword'
