#!/usr/bin/env ruby

ENV['APP_ROOT'] ||= File.expand_path(File.join(File.dirname(__FILE__), '..'))
APP_ROOT = ENV['APP_ROOT']
script_file = File.join(APP_ROOT, 'lib', 'poller.rb')
tmp_dir = File.join(APP_ROOT, 'tmp')
log_dir = File.join(APP_ROOT, 'log')

require 'rubygems'
require 'daemons'
require 'active_support'

process_group = ARGV.select{|p| p.match(/process-group/)}.first.to_s
app_name = "#{process_group.match(/.*=(.*)/)[1]}-poller" if !process_group.empty?
app_name = 'poller' if app_name.nil?

options = {
  :app_name   => app_name,
  :dir_mode   => :normal,
  :dir        => tmp_dir,
  :multiple   => true,
  :ontop      => false,
  :mode       => :load,
  :backtrace  => true,
  :monitor    => false,
  :log_dir    => log_dir,
  :log_output => true
}

Daemons.run(script_file,options)
